### ISSUE TITLE
Defaults to 30 degrees

### ISSUE THREAD

**Issue by dgaust** [ckuburlis/homebridge-tado#12]
Hi,

In the home app, whenever I open the TADO accessory, it defaults the slider to 30 degrees. Is there a way for this to default to the current selected temperature?

**Comment by nitaybz** [comment]
@dgaust solved in the last update
please update your plugin with
`sudo npm install -g https://github.com/ckuburlis/homebridge-tado.git`

**Comment by jadomski** [comment]
I've updated to the latest git commit, but the issue is still there for me.

**Update:** It now works properly after removing the accessory from HomeKit and re-adding it.
